name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Compile TypeScript
      run: npm run compile

    - name: Setup display for VS Code tests
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libnss3-dev libatk-bridge2.0-dev libdrm2 libxkbcommon-dev libxss1 libasound2-dev

    - name: Run tests
      run: xvfb-run -a npm run test:ci
      env:
        DISPLAY: ':99.0'
        CI: 'true'
      continue-on-error: false

    - name: Package extension
      run: npm run package

    - name: Upload VSIX artifact
      uses: actions/upload-artifact@v4
      if: matrix.node-version == '18.x'
      with:
        name: vsix-package
        path: '*.vsix'
        retention-days: 30
