name: Publish to Marketplace

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., patch, minor, major, or specific version like 1.0.0)'
        required: true
        default: 'patch'
        type: string

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: Compile TypeScript
      run: npm run compile
      
    - name: Setup display for VS Code tests
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libnss3-dev libatk-bridge2.0-dev libdrm2 libxkbcommon-dev libxss1 libasound2-dev
        
    - name: Run tests
      run: xvfb-run -a npm run test:ci
      env:
        DISPLAY: ':99.0'
        CI: 'true'
        
    - name: Publish to VS Code Marketplace
      run: |
        if [ "${{ github.event_name }}" = "release" ]; then
          # Publish the current version for releases
          npx vsce publish --no-git-tag-version
        else
          # Publish with version bump for manual dispatch
          npx vsce publish ${{ inputs.version }}
        fi
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
        
    - name: Package extension
      run: npx vsce package
      
    - name: Upload VSIX artifact
      uses: actions/upload-artifact@v4
      with:
        name: vsix-package
        path: '*.vsix'
        retention-days: 30
