name: Publish to Marketplace

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., patch, minor, major, or specific version like 1.0.0)'
        required: true
        default: 'patch'
        type: string
      dry_run:
        description: 'Dry run (package only, do not publish)'
        required: false
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: Compile TypeScript
      run: npm run compile
      
    - name: Setup display for VS Code tests
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libnss3-dev libatk-bridge2.0-dev libdrm2 libxkbcommon-dev libxss1 libasound2-dev
        
    - name: Run tests
      run: xvfb-run -a npm run test:ci
      env:
        DISPLAY: ':99.0'
        CI: 'true'
        NODE_ENV: 'test'
        
    - name: Verify VSCE_PAT secret
      run: |
        if [ -z "${{ secrets.VSCE_PAT }}" ]; then
          echo "❌ VSCE_PAT secret is not set"
          echo "Please add your Personal Access Token as a repository secret named 'VSCE_PAT'"
          echo "See: https://docs.github.com/en/actions/security-guides/encrypted-secrets"
          exit 1
        else
          echo "✅ VSCE_PAT secret is configured"
        fi

    - name: Package extension
      run: npx vsce package
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}

    - name: Publish to VS Code Marketplace
      if: ${{ !inputs.dry_run }}
      run: |
        echo "🚀 Publishing to VS Code Marketplace..."
        if [ "${{ github.event_name }}" = "release" ]; then
          # Publish the current version for releases
          echo "📦 Publishing current version from release"
          npx vsce publish --no-git-tag-version
        else
          # Publish with version bump for manual dispatch
          echo "📦 Publishing with version: ${{ inputs.version }}"
          npx vsce publish ${{ inputs.version }}
        fi
        echo "✅ Successfully published to marketplace"
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}

    - name: Dry run summary
      if: ${{ inputs.dry_run }}
      run: |
        echo "🔍 Dry run completed - extension was packaged but not published"
        echo "To publish, run this workflow again with 'Dry run' unchecked"
      
    - name: Upload VSIX artifact
      uses: actions/upload-artifact@v4
      with:
        name: vsix-package
        path: '*.vsix'
        retention-days: 30
